services:
  db:
    image: postgres:14.18
    container_name: article-mgmt-backend-db-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2003 
    ports:
      - 5433:5432
    volumes:
      - "article_mgmt_backend_data:/var/lib/postgresql/data"
    networks:
      - article_mgmt_backend_network

  # backend:
  #   build: .
  #   container_name: product-orders-mgmt-container
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://article-mgmt-backend-db-container:5432/postgres
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: 2003
  #   ports:
  #     - 8081:8090
  #   depends_on:
  #     - db
  #   networks:
  #     - article_mgmt_backend_network

networks:
  article_mgmt_backend_network:
    driver: bridge

volumes:
  article_mgmt_backend_data: